model:
  agent:
    provider: openai
    name: doubao-seed-1-6-251015
    api_base: https://ark.cn-beijing.volces.com/api/v3/
    api_key: 'xxxx'

volcengine:
  # [optional] for Viking DB and `web_search` tool
  access_key: xxxx
  secret_key: xxxx